image: node:14-alpine

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

stages:
  - build

build:
  stage: build
  tags:
    - docker

  script:
    - cd src
    - npm install

##test: NOT REQUIRED
  ##stage: test
  ##tags:
    ##- docker
  ##services:
    ##- name: mvertes/alpine-mongo:latest
      ##alias: mongo
  ##variables:
    ##MONGODB_URI: "mongodb://mongo:27017/serverTestDB"
  ##script:
    ##- cd src
    ##- npm run ci-test
